name: sahand_warehouse
description: اپلیکیشن مدیریت انبار سهند
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/ic_launcher_192x192.png"
  image_path_ios: "assets/icons/ic_launcher_192x192.png"
